
version: '3.4'

services:
  estimatz.com:
    image: josuecardosodev/estimatz.com
    ports:
      - 5000:80
      - 5001:443
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_Kestrel__Certificates__Default__Password=pa55w0rd!
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/teste-estimatz/MyLearn.APIApp.pfx