
version: '3.4'

services:
  estimatz.login.api:
    image: estimatz.login.api
    ports:
      - 5000:80
      - 5001:443
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_Kestrel__Certificates__Default__Password=pa55w0rd!
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/MyLearn.APIApp.pfx
    volumes:
      - ~/.aspnet/https:/https:ro

  estimatz.ui:
    image: estimatz.ui
    ports:
      - 8080:80
      - 8081:443
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_Kestrel__Certificates__Default__Password=pa55w0rd!
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/MyLearn.APIApp.pfx
    volumes:
      - ~/.aspnet/https:/https:ro