trigger:
- develop

pool:
  name: 'PC-1'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1
  
- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactStagingDirectory)"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- script: dotnet test Estimatz\Tests\Estimatz.Test\Estimatz.Test.UnitTest.csproj --configuration $(buildConfiguration) --logger trx --collect:"XPlat Code Coverage"
  displayName: 'Run Unit Tests with Coverage'

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'VSTest'
    testResultsFiles: '**/*.trx'
    failTaskOnFailedTests: true
  displayName: 'Publish Test Results'
  
- task: PublishCodeCoverageResults@1
  inputs:
      codeCoverageTool: 'Cobertura'
      summaryFileLocation: '**/*.cobertura.xml'
      reportDirectory: '$(Build.ArtifactStagingDirectory)/CodeCoverage'
  displayName: 'Publish Code Coverage'
