//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Estimatz.UI.Resources.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class es_es {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal es_es() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Estimatz.UI.Resources.Languages.es-es", typeof(es_es).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sobre nosotros.
        /// </summary>
        internal static string AboutUsPage {
            get {
                return ResourceManager.GetString("AboutUsPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se le ha enviado un correo electrónico de confirmación.
        /// </summary>
        internal static string AccountCreatedMessage01 {
            get {
                return ResourceManager.GetString("AccountCreatedMessage01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Para confirmar y acceder a su nueva cuenta, simplemente haga clic en el enlace del correo electrónico..
        /// </summary>
        internal static string AccountCreatedMessage02 {
            get {
                return ResourceManager.GetString("AccountCreatedMessage02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¡Nueva cuenta creada con éxito!.
        /// </summary>
        internal static string AccountCreatedSuccessfully {
            get {
                return ResourceManager.GetString("AccountCreatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor, intente de nuevo en unos momentos o póngase en contacto con nuestro soporte!.
        /// </summary>
        internal static string AccountNotCreatedMessage01 {
            get {
                return ResourceManager.GetString("AccountNotCreatedMessage01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pudo crear la cuenta..
        /// </summary>
        internal static string AccountNotCreatedSuccessfully {
            get {
                return ResourceManager.GetString("AccountNotCreatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocurrió el siguiente error:.
        /// </summary>
        internal static string AnErrorOcurred {
            get {
                return ResourceManager.GetString("AnErrorOcurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vuelve a la página de inicio para iniciar sesión..
        /// </summary>
        internal static string BackToHomePageForSignIn {
            get {
                return ResourceManager.GetString("BackToHomePageForSignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmar contraseña.
        /// </summary>
        internal static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¡No se pudo recuperar su contraseña!.
        /// </summary>
        internal static string CouldNotRecoverYourPassword {
            get {
                return ResourceManager.GetString("CouldNotRecoverYourPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registrarte.
        /// </summary>
        internal static string CreateAccount {
            get {
                return ResourceManager.GetString("CreateAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crear nueva cuenta.
        /// </summary>
        internal static string CreateNewAccount {
            get {
                return ResourceManager.GetString("CreateNewAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crear nueva sala.
        /// </summary>
        internal static string CreateNewRoom {
            get {
                return ResourceManager.GetString("CreateNewRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Establecer contraseña.
        /// </summary>
        internal static string CreatePassword {
            get {
                return ResourceManager.GetString("CreatePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se produjo un error desconocido.
        /// </summary>
        internal static string DefaultError {
            get {
                return ResourceManager.GetString("DefaultError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿No quieres registrarte? Intertalo:.
        /// </summary>
        internal static string DontRegister {
            get {
                return ResourceManager.GetString("DontRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este correo electrónico ya está en uso.
        /// </summary>
        internal static string DuplicateEmail {
            get {
                return ResourceManager.GetString("DuplicateEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este e-mail já está sendo utilizado.
        /// </summary>
        internal static string DuplicateUserName {
            get {
                return ResourceManager.GetString("DuplicateUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmación de correo electrónico.
        /// </summary>
        internal static string EmailConfirmation {
            get {
                return ResourceManager.GetString("EmailConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¡Email confirmado exitosamente!.
        /// </summary>
        internal static string EmailConfirmedSuccessfully {
            get {
                return ResourceManager.GetString("EmailConfirmedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¡No se pudo confirmar el correo electrónico!.
        /// </summary>
        internal static string EmailNotConfirmedSuccessfully {
            get {
                return ResourceManager.GetString("EmailNotConfirmedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inglés.
        /// </summary>
        internal static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enviar.
        /// </summary>
        internal static string Finalize {
            get {
                return ResourceManager.GetString("Finalize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Perdiste tu contraseña?.
        /// </summary>
        internal static string ForgetPassword {
            get {
                return ResourceManager.GetString("ForgetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regresar.
        /// </summary>
        internal static string GoBack {
            get {
                return ResourceManager.GetString("GoBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volver a la página de inicio.
        /// </summary>
        internal static string GoBackToHomePage {
            get {
                return ResourceManager.GetString("GoBackToHomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inicio.
        /// </summary>
        internal static string HomePage {
            get {
                return ResourceManager.GetString("HomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingrese su correo electrónico a continuación para recibir instrucciones sobre cómo recuperar su contraseña.
        /// </summary>
        internal static string InsertYourEmailMessage {
            get {
                return ResourceManager.GetString("InsertYourEmailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este correo electrónico no es válido.
        /// </summary>
        internal static string InvalidEmail {
            get {
                return ResourceManager.GetString("InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token inválido.
        /// </summary>
        internal static string InvalidToken {
            get {
                return ResourceManager.GetString("InvalidToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idioma.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iniciar sesión.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ya existe un usuario con este inicio de sesión.
        /// </summary>
        internal static string LoginAlreadyAssociated {
            get {
                return ResourceManager.GetString("LoginAlreadyAssociated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minúscula.
        /// </summary>
        internal static string LowerCaseLetter {
            get {
                return ResourceManager.GetString("LowerCaseLetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mínimo de 8 caracteres.
        /// </summary>
        internal static string MinimumCharacter {
            get {
                return ResourceManager.GetString("MinimumCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nueva contraseña.
        /// </summary>
        internal static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿No tienes cuenta?.
        /// </summary>
        internal static string NotHaveAccount {
            get {
                return ResourceManager.GetString("NotHaveAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número.
        /// </summary>
        internal static string Number {
            get {
                return ResourceManager.GetString("Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O.
        /// </summary>
        internal static string Or {
            get {
                return ResourceManager.GetString("Or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contraseña.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Las contraseñas deben contener al menos un dígito (&apos;0&apos;-&apos;9&apos;).
        /// </summary>
        internal static string PasswordRequiresDigit {
            get {
                return ResourceManager.GetString("PasswordRequiresDigit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Las contraseñas deben contener al menos una letra minúscula (&apos;a&apos;-&apos;z&apos;).
        /// </summary>
        internal static string PasswordRequiresLower {
            get {
                return ResourceManager.GetString("PasswordRequiresLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Las contraseñas deben contener al menos un carácter no alfanumérico.
        /// </summary>
        internal static string PasswordRequiresNonAlphanumeric {
            get {
                return ResourceManager.GetString("PasswordRequiresNonAlphanumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Las contraseñas deben contener al menos una letra mayúscula (&apos;A&apos;-&apos;Z&apos;).
        /// </summary>
        internal static string PasswordRequiresUpper {
            get {
                return ResourceManager.GetString("PasswordRequiresUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¡Contraseña recuperada con éxito!.
        /// </summary>
        internal static string PasswordSuccessfullyRecovered {
            get {
                return ResourceManager.GetString("PasswordSuccessfullyRecovered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portugués.
        /// </summary>
        internal static string Portuguese {
            get {
                return ResourceManager.GetString("Portuguese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precios.
        /// </summary>
        internal static string PricingPage {
            get {
                return ResourceManager.GetString("PricingPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Juego Rápido.
        /// </summary>
        internal static string QuickPlay {
            get {
                return ResourceManager.GetString("QuickPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recuperar contraseña.
        /// </summary>
        internal static string RecoveryPassword {
            get {
                return ResourceManager.GetString("RecoveryPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID de la sala.
        /// </summary>
        internal static string RoomId {
            get {
                return ResourceManager.GetString("RoomId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardar nueva contraseña.
        /// </summary>
        internal static string SaveNewPassword {
            get {
                return ResourceManager.GetString("SaveNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enviar.
        /// </summary>
        internal static string SendEmail {
            get {
                return ResourceManager.GetString("SendEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Español.
        /// </summary>
        internal static string Spanish {
            get {
                return ResourceManager.GetString("Spanish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carácter especial.
        /// </summary>
        internal static string SpecialCharacter {
            get {
                return ResourceManager.GetString("SpecialCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teste - Espanhol.
        /// </summary>
        internal static string Teste {
            get {
                return ResourceManager.GetString("Teste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mayúscula.
        /// </summary>
        internal static string UpperCaseLetter {
            get {
                return ResourceManager.GetString("UpperCaseLetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¡Bienvenido a Estimatz!.
        /// </summary>
        internal static string WelcomeToEstimatz {
            get {
                return ResourceManager.GetString("WelcomeToEstimatz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tu nombre.
        /// </summary>
        internal static string YourName {
            get {
                return ResourceManager.GetString("YourName", resourceCulture);
            }
        }
    }
}
