//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Estimatz.UI.Resources.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class pt_br {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal pt_br() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Estimatz.UI.Resources.Languages.pt-br", typeof(pt_br).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sobre Nós.
        /// </summary>
        internal static string AboutUsPage {
            get {
                return ResourceManager.GetString("AboutUsPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Um e-mail de confirmação foi enviado para você!.
        /// </summary>
        internal static string AccountCreatedMessage01 {
            get {
                return ResourceManager.GetString("AccountCreatedMessage01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Para confirmar e realizar login com sua nova conta basta clicar no link do e-mail..
        /// </summary>
        internal static string AccountCreatedMessage02 {
            get {
                return ResourceManager.GetString("AccountCreatedMessage02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nova conta criada com sucesso!.
        /// </summary>
        internal static string AccountCreatedSuccessfully {
            get {
                return ResourceManager.GetString("AccountCreatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tente novamente em alguns instantes ou entre em contato com nosso suporte!.
        /// </summary>
        internal static string AccountNotCreatedMessage01 {
            get {
                return ResourceManager.GetString("AccountNotCreatedMessage01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi possível criar a conta!.
        /// </summary>
        internal static string AccountNotCreatedSuccessfully {
            get {
                return ResourceManager.GetString("AccountNotCreatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu o seguinte erro:.
        /// </summary>
        internal static string AnErrorOcurred {
            get {
                return ResourceManager.GetString("AnErrorOcurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retorne a página inicial para realizer login..
        /// </summary>
        internal static string BackToHomePageForSignIn {
            get {
                return ResourceManager.GetString("BackToHomePageForSignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmar senha.
        /// </summary>
        internal static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi possível recuperar a sua senha!.
        /// </summary>
        internal static string CouldNotRecoverYourPassword {
            get {
                return ResourceManager.GetString("CouldNotRecoverYourPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Criar conta.
        /// </summary>
        internal static string CreateAccount {
            get {
                return ResourceManager.GetString("CreateAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Criar nova conta.
        /// </summary>
        internal static string CreateNewAccount {
            get {
                return ResourceManager.GetString("CreateNewAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Criar nova sala .
        /// </summary>
        internal static string CreateNewRoom {
            get {
                return ResourceManager.GetString("CreateNewRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Definir senha.
        /// </summary>
        internal static string CreatePassword {
            get {
                return ResourceManager.GetString("CreatePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu um erro desconhecido.
        /// </summary>
        internal static string DefaultError {
            get {
                return ResourceManager.GetString("DefaultError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não quer se registrar? Experimente:.
        /// </summary>
        internal static string DontRegister {
            get {
                return ResourceManager.GetString("DontRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este e-mail já está sendo utilizado.
        /// </summary>
        internal static string DuplicateEmail {
            get {
                return ResourceManager.GetString("DuplicateEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este e-mail já está sendo utilizado.
        /// </summary>
        internal static string DuplicateUserName {
            get {
                return ResourceManager.GetString("DuplicateUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmação de e-mail.
        /// </summary>
        internal static string EmailConfirmation {
            get {
                return ResourceManager.GetString("EmailConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email confirmado com sucesso!.
        /// </summary>
        internal static string EmailConfirmedSuccessfully {
            get {
                return ResourceManager.GetString("EmailConfirmedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi possível confirmar o e-mail!.
        /// </summary>
        internal static string EmailNotConfirmedSuccessfully {
            get {
                return ResourceManager.GetString("EmailNotConfirmedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi possível enviar o e-mail!.
        /// </summary>
        internal static string EmailNotSent {
            get {
                return ResourceManager.GetString("EmailNotSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail enviado!.
        /// </summary>
        internal static string EmailSent {
            get {
                return ResourceManager.GetString("EmailSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inglês.
        /// </summary>
        internal static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finalizar.
        /// </summary>
        internal static string Finalize {
            get {
                return ResourceManager.GetString("Finalize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esqueceu a senha?.
        /// </summary>
        internal static string ForgetPassword {
            get {
                return ResourceManager.GetString("ForgetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voltar.
        /// </summary>
        internal static string GoBack {
            get {
                return ResourceManager.GetString("GoBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voltar a página inicial.
        /// </summary>
        internal static string GoBackToHomePage {
            get {
                return ResourceManager.GetString("GoBackToHomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Início.
        /// </summary>
        internal static string HomePage {
            get {
                return ResourceManager.GetString("HomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insira seu e-mail abaixo para receber instruções de como recuperar sua senha.
        /// </summary>
        internal static string InsertYourEmailMessage {
            get {
                return ResourceManager.GetString("InsertYourEmailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail com as instruções enviado para:.
        /// </summary>
        internal static string InstructionsSendTo {
            get {
                return ResourceManager.GetString("InstructionsSendTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esté e-mail é inválido.
        /// </summary>
        internal static string InvalidEmail {
            get {
                return ResourceManager.GetString("InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token inválido.
        /// </summary>
        internal static string InvalidToken {
            get {
                return ResourceManager.GetString("InvalidToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idioma.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entrar.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Já existe um usuário com este login.
        /// </summary>
        internal static string LoginAlreadyAssociated {
            get {
                return ResourceManager.GetString("LoginAlreadyAssociated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Letra minúscula.
        /// </summary>
        internal static string LowerCaseLetter {
            get {
                return ResourceManager.GetString("LowerCaseLetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mínimo 8 caracteres.
        /// </summary>
        internal static string MinimumCharacter {
            get {
                return ResourceManager.GetString("MinimumCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nova senha.
        /// </summary>
        internal static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não possui conta ainda?.
        /// </summary>
        internal static string NotHaveAccount {
            get {
                return ResourceManager.GetString("NotHaveAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número.
        /// </summary>
        internal static string Number {
            get {
                return ResourceManager.GetString("Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ou.
        /// </summary>
        internal static string Or {
            get {
                return ResourceManager.GetString("Or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senha.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senhas devem conter ao menos um digito (&apos;0&apos;-&apos;9&apos;).
        /// </summary>
        internal static string PasswordRequiresDigit {
            get {
                return ResourceManager.GetString("PasswordRequiresDigit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senhas devem conter ao menos um caracter em caixa baixa (&apos;a&apos;-&apos;z&apos;).
        /// </summary>
        internal static string PasswordRequiresLower {
            get {
                return ResourceManager.GetString("PasswordRequiresLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senhas devem conter ao menos um caracter não alfanumérico.
        /// </summary>
        internal static string PasswordRequiresNonAlphanumeric {
            get {
                return ResourceManager.GetString("PasswordRequiresNonAlphanumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senhas devem conter ao menos um caracter em caixa alta (&apos;A&apos;-&apos;Z&apos;).
        /// </summary>
        internal static string PasswordRequiresUpper {
            get {
                return ResourceManager.GetString("PasswordRequiresUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senha recuperada com sucesso!.
        /// </summary>
        internal static string PasswordSuccessfullyRecovered {
            get {
                return ResourceManager.GetString("PasswordSuccessfullyRecovered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Português.
        /// </summary>
        internal static string Portuguese {
            get {
                return ResourceManager.GetString("Portuguese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preços.
        /// </summary>
        internal static string PricingPage {
            get {
                return ResourceManager.GetString("PricingPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sala instantânea.
        /// </summary>
        internal static string QuickPlay {
            get {
                return ResourceManager.GetString("QuickPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recuperar Senha.
        /// </summary>
        internal static string RecoveryPassword {
            get {
                return ResourceManager.GetString("RecoveryPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID da sala.
        /// </summary>
        internal static string RoomId {
            get {
                return ResourceManager.GetString("RoomId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salvar nova senha.
        /// </summary>
        internal static string SaveNewPassword {
            get {
                return ResourceManager.GetString("SaveNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enviar e-mail.
        /// </summary>
        internal static string SendEmail {
            get {
                return ResourceManager.GetString("SendEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Espanhol.
        /// </summary>
        internal static string Spanish {
            get {
                return ResourceManager.GetString("Spanish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caractere Especial.
        /// </summary>
        internal static string SpecialCharacter {
            get {
                return ResourceManager.GetString("SpecialCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teste - Português.
        /// </summary>
        internal static string Teste {
            get {
                return ResourceManager.GetString("Teste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Letra maiúscula.
        /// </summary>
        internal static string UpperCaseLetter {
            get {
                return ResourceManager.GetString("UpperCaseLetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bem-vindo ao Estimatz!.
        /// </summary>
        internal static string WelcomeToEstimatz {
            get {
                return ResourceManager.GetString("WelcomeToEstimatz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seu nome.
        /// </summary>
        internal static string YourName {
            get {
                return ResourceManager.GetString("YourName", resourceCulture);
            }
        }
    }
}
